---
# This playbook deploys the whole application stack in this site.
- hosts: all
  remote_user: ansible
  roles:
    - common

#- hosts: webservers
#  tasks:
#  - name: configure and deploy the webservers and application code
#    remote_user: ansible
#    roles:
#    - web

#- hosts: dbservers
#  tasks:
#  - name: deploy MySQL and configure the databases
#    hosts: dbservers
#    remote_user: ansible
#    roles:
#    - db
