
# This playbook contains common plays that will be run on all nodes.
- hosts: all

  tasks:
  - name: Install MariaDB package
    yum: name=ntp state=present
    tags: ntp

  - name: Install common dependencies
    yum:
      name: "{{ item }}"
      state: install
      with_items:
            - libselinux-python
            - libsemanage-python
            - firewalld

  - name: Configure ntp file
    template: src=ntp.conf.j2 dest=/etc/ntp.conf
    tags: ntp
    notify: restart ntp

  handlers:
    - name: Start the ntp servicio
      service: name=ntp state=restarted
      tags: ntp

