# This playbook contains common plays that will be run on all nodes.
  - name: Install Chrony
    yum: name=chrony state=present
    tags: ntp/chrony

  - name: Install common dependencies
    yum:
      name: 
            - firewalld
      state: present

  - name: Configure ntp file
    template: 
      src: /home/ansible/ansible/obligatorio_2021_08/lamp/roles/common/templates/ntp.conf.j2
      dest: /etc/ntp.conf
    tags: ntp
    notify: restart chronyd
