---
# This playbook will install MariaDB and create db user and give permissions.
  - name: Install MariaDB package
    yum: 
      name: "mariadb" 
      state: present
    with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb
      - python2-PyMySQL
    
  - name: Configure SELinux to start mysql on any port
    seboolean: name=mysql_connect_any state=true persistent=yes

  - name: Create Mysql configuration file
    template: src=my.cnf.j2 dest=/var/lib/mysql
    notify:
    - restart mariadb

  - name: Create MariaDB log file
    file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

  - name: Create MariaDB PID directory
    file: path=/var/run/mysqld state=touch owner=mysql group=mysql mode=0775

  - name: Start MariaDB Service
    service: name=mariadb state=started enabled=yes

  - name: Start firewalld
    service: name=firewalld state=started enabled=yes

  - name: insert firewalld rule
    firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
      
  - name: Create Application Database
    mysql_db: name={{ dbname }} 
      state=present 
      login_user=foouser 
      login_password=abc 
    #login_unix_socket= 

  - name: Create Application DB User
    mysql_user: 
      name={{ dbuser }} 
      password={{ upassword }} 
      priv=*.*:ALL 
      host='%' state=present